[package]
name = "snap-ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
arboard = "3.6.1"
dirs = "6.0.0"
dotenvy = "0.15.7"
global-hotkey = "0.8.0"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "multipart", "query", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tao = "0.35.3"
tray-icon = "0.24.1"
